FROM alpine
WORKDIR /mnt
RUN apk -U add php7 php7-json php7-phar php7-iconv php7-openssl php7-zlib
ADD https://getcomposer.org/installer /tmp/composer-setup.php
RUN php7 /tmp/composer-setup.php && rm /tmp/composer-setup.php
CMD php7 -S 0.0.0.0:80
